[info]
    from=""        # 发件人邮箱
    to=""          # 收件人邮箱
    auth_code=""    # 发件人邮箱的授权码

[server]
    smtp="smtp.qq.com"          # 邮件服务器地址
    port=465                    # 邮件服务器端口

[timer]     # 定时器
    task_count = 2                      # 启用定时任务时，设置定时任务数量
                                        #  <0 认为执行无限次 | 0 认为不执行发送 | 1 认为不开启定时一次执行 | >=1 执行看对应次数
    start_time = "2024-08-21 23:50:00"  # 定时任务开始时间
    [timer.time_interval]               # 定时任务间隔时间
        year = 0        #（年）
        month = 0       #（月）
        day = 0         #（天）
        hour = 0       # (时）
        minute = 1      #（分）
        second = 0      #（秒）